# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'surfalytics_dbt_core'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'surfalytics_dbt_core'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  surfalytics_dbt_core:
    # Legacy example models
    example:
      +materialized: view

    # STAGING LAYER
    # Light transformations, one model per source table
    # Materialized as views for freshness
    staging:
      +materialized: view
      +schema: staging
      +tags: ["staging"]

    # INTERMEDIATE LAYER
    # Business logic, joins, reusable building blocks
    # Materialized as views by default, tables for performance-critical models
    intermediate:
      +materialized: view
      +schema: intermediate
      +tags: ["intermediate"]
      orders:
        +materialized: table  # Performance optimization for frequently-used models
      customers:
        int_customers__order_aggregates:
          +materialized: table  # Performance optimization

    # MARTS LAYER
    # Business-facing analytics models
    # Materialized as tables for query performance
    marts:
      +materialized: table
      +tags: ["marts"]
      customers:
        +schema: customers
      products:
        +schema: products
        order_items:
          +materialized: incremental  # Incremental for large fact table
seeds:
  surfalytics_dbt_core:
    +schema: raw_jaffle_shop

vars:
  dbt_date:time_zone: 'America/New_York'

flags:
  require_generic_test_arguments_property: true