version: 2

models:
  - name: product_performance
    description: >
      **Product Performance Summary**

      Aggregated product sales metrics and profitability analysis.
      Ranks products by revenue and shows key performance indicators.

      **Grain**: One row per product SKU

      **Use Cases**:
      - Product ranking and comparison
      - Menu optimization decisions
      - Inventory planning
      - Marketing prioritization
    columns:
      - name: sku
        description: Product SKU code (primary key)

      - name: product_name
        description: Product display name

      - name: product_type
        description: Product category

      - name: price
        description: Product selling price

      - name: total_supply_cost
        description: Cost per unit

      - name: gross_margin
        description: Gross margin percentage

      - name: total_items_sold
        description: Total quantity sold across all time

      - name: total_revenue
        description: Total revenue generated by this product

      - name: num_orders_containing_product
        description: Number of distinct orders that included this product

      - name: avg_items_per_order
        description: Average quantity of this product per order

      - name: first_sale_at
        description: Timestamp of first sale of this product

      - name: most_recent_sale_at
        description: Timestamp of most recent sale

      - name: total_cost
        description: Total cost of goods sold (units * unit cost)

      - name: total_profit
        description: Total gross profit (revenue - total cost)

      - name: revenue_rank
        description: Product ranking by total revenue (1 = highest)
    config:
      meta:
        owner: analytics
        domain: product_analytics